name: Firmware Build
run-name: ${{ github.actor }} is building your firmware ğŸš€
on: [push, workflow_dispatch]
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        run: git clone git@github.com:waterloop/${{ github.repository }}
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Test Build
        with:
          image: quinn1876/waterloop-firmware:latest
          options: -v ${{ github.workspace }}:/firmware
          run: |
            python3 ./scripts/build-all.py
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      
